# Generated by Django 4.2.19 on 2025-02-21 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('reason', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.FloatField(default=0.0, help_text='Risk score from 0 to 1')),
            ],
            options={
                'verbose_name': 'Blacklisted Address',
                'verbose_name_plural': 'Blacklisted Addresses',
            },
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crypto Wallet',
                'verbose_name_plural': 'Crypto Wallets',
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('frozen', 'Frozen')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('transaction_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Batch',
                'verbose_name_plural': 'Payment Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.ImageField(null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Payment Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('payment_detected_at', models.DateTimeField(null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_payments.cryptowallet')),
            ],
            options={
                'verbose_name': 'Deposit Address',
                'verbose_name_plural': 'Deposit Addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=20)),
                ('amount_crypto', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='crypto_payments.cryptowallet')),
            ],
            options={
                'verbose_name': 'Crypto Transaction',
                'verbose_name_plural': 'Crypto Transactions',
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('freeze_wallet', 'Freeze Wallet'), ('unfreeze_wallet', 'Unfreeze Wallet'), ('freeze_batch', 'Freeze Payment Batch'), ('unfreeze_batch', 'Unfreeze Payment Batch'), ('approve_withdrawal', 'Approve Withdrawal'), ('reject_withdrawal', 'Reject Withdrawal'), ('blacklist_address', 'Blacklist Address'), ('other', 'Other Action')], max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action',
                'verbose_name_plural': 'Admin Actions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BatchTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_payments.paymentbatch')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_payments.cryptotransaction')),
            ],
            options={
                'verbose_name': 'Batch Transaction',
                'verbose_name_plural': 'Batch Transactions',
                'unique_together': {('batch', 'transaction')},
            },
        ),
    ]
