# Generated by Django 4.2.19 on 2025-02-21 23:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('delivery_type', models.CharField(choices=[('instant', 'Instant Delivery'), ('mail', 'Mail Delivery'), ('pickup', 'Pickup')], max_length=20)),
                ('delivery_address', models.TextField(max_length=500)),
                ('delivery_instructions', models.TextField(blank=True, max_length=500)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('BTC', 'Bitcoin'), ('XMR', 'Monero'), ('USDT', 'Tether')], default='USD', max_length=4)),
                ('country', models.CharField(blank=True, choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('DE', 'Germany'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('NL', 'Netherlands')], max_length=2)),
                ('pgp_key', models.TextField(blank=True)),
                ('pgp_verified', models.BooleanField(default=False)),
                ('transaction_pin', models.CharField(blank=True, max_length=6)),
                ('pin_last_changed', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), help_text='BTC balance', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('xmr_balance', models.DecimalField(decimal_places=12, default=Decimal('0.0'), help_text='XMR balance', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('usdt_balance', models.DecimalField(decimal_places=6, default=Decimal('0.0'), help_text='USDT balance', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='marketplace.userprofile')),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User Wallets',
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('bond_paid', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_ratings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('instant_delivery', models.BooleanField(default=False)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pickup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_delivery_distance', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('min_order_quantity', models.IntegerField(default=1)),
                ('max_order_quantity', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_mode', models.BooleanField(default=False, help_text='Enable to temporarily close store')),
                ('vacation_message', models.TextField(blank=True, help_text='Message to display when store is in vacation mode')),
                ('vacation_start', models.DateTimeField(blank=True, null=True)),
                ('vacation_end', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.vendorprofile')),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
        migrations.CreateModel(
            name='OrderTimeframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('mail', 'Mail Delivery'), ('pickup', 'Pickup'), ('instant', 'Instant Delivery')], help_text='Type of delivery', max_length=20)),
                ('base_days', models.IntegerField(help_text='Base number of days for order completion', validators=[django.core.validators.MinValueValidator(0)])),
                ('extended_days', models.IntegerField(default=0, help_text='Additional days requested by buyer', validators=[django.core.validators.MinValueValidator(0)])),
                ('auto_finalize_at', models.DateTimeField(help_text='When this order will automatically finalize')),
                ('last_extended', models.DateTimeField(blank=True, help_text='When the timeframe was last extended', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeframe', to='marketplace.deliveryorder')),
            ],
            options={
                'verbose_name': 'Order Timeframe',
                'verbose_name_plural': 'Order Timeframes',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('shipped', 'Shipped'), ('finalized', 'Finalized'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], help_text='Current status of the order', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When this status was set')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this status change')),
                ('changed_by', models.ForeignKey(help_text='User who changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='marketplace.deliveryorder')),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
                'ordering': ['-changed_at'],
                'get_latest_by': 'changed_at',
            },
        ),
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(choices=[('quality', 'Product Quality'), ('delivery', 'Delivery Issues'), ('other', 'Other Issues')], max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.deliveryorder')),
            ],
            options={
                'verbose_name': 'Order Dispute',
                'verbose_name_plural': 'Order Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveDeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_mode', models.CharField(choices=[('realtime', 'Real-time GPS'), ('manual', 'Manual Updates')], default='manual', help_text='Current tracking mode', max_length=10)),
                ('driver_name', models.CharField(help_text='Name of delivery driver', max_length=100)),
                ('driver_photo', models.ImageField(blank=True, help_text='Photo of delivery driver', null=True, upload_to='driver_photos/')),
                ('current_latitude', models.DecimalField(decimal_places=6, help_text='Current latitude of driver', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('current_longitude', models.DecimalField(decimal_places=6, help_text='Current longitude of driver', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('estimated_arrival', models.DateTimeField(help_text='Estimated time of arrival')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When location was last updated')),
                ('delivery_notes', models.TextField(blank=True, help_text='Any special delivery instructions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tracking is currently active')),
                ('order', models.OneToOneField(help_text='The order being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='live_tracking', to='marketplace.deliveryorder')),
            ],
            options={
                'verbose_name': 'Live Delivery Tracking',
                'verbose_name_plural': 'Live Delivery Tracking',
            },
        ),
        migrations.CreateModel(
            name='DisputeQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requires_admin', models.BooleanField(default=False, help_text='Only admins can handle disputes in this queue')),
                ('support_staff', models.ManyToManyField(limit_choices_to={'is_staff': True}, related_name='dispute_queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Queue',
                'verbose_name_plural': 'Dispute Queues',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('escalated', 'Escalated to Admin'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.deliveryorder')),
                ('queue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.disputequeue')),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique discount code', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Description of the discount')),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When this discount becomes valid')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When this discount expires (optional)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', help_text='Current status of the discount code', max_length=20)),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of times this code can be used (optional)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_uses', models.IntegerField(default=0, help_text='Number of times this code has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='marketplace.vendorprofile')),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('status_update', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.deliveryorder')),
            ],
            options={
                'verbose_name': 'Delivery Tracking',
                'verbose_name_plural': 'Delivery Tracking',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.vendorproduct'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.vendorprofile'),
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this location was recorded')),
                ('tracking', models.ForeignKey(help_text='The tracking record this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='marketplace.livedeliverytracking')),
            ],
            options={
                'verbose_name': 'Delivery Location',
                'verbose_name_plural': 'Delivery Locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('btc', 'Bitcoin'), ('xmr', 'Monero'), ('usdt', 'USDT')], help_text='Cryptocurrency type', max_length=4)),
                ('address', models.CharField(help_text='Withdrawal address', max_length=128)),
                ('is_flagged', models.BooleanField(default=False, help_text='Whether this address has been flagged for suspicious activity')),
                ('flag_reason', models.TextField(blank=True, help_text='Reason for flagging this address')),
                ('used_by_other_accounts', models.BooleanField(default=False, help_text='Whether this address has been used by other accounts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_addresses', to='marketplace.userwallet')),
            ],
            options={
                'verbose_name': 'Withdrawal Address',
                'verbose_name_plural': 'Withdrawal Addresses',
                'unique_together': {('wallet', 'currency', 'address')},
            },
        ),
    ]
