# Generated by Django 4.2.19 on 2025-02-21 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Business name (max 100 characters)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Business description (max 2000 characters)', max_length=2000)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='pending', max_length=20)),
                ('bond_amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('bond_paid', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
            },
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=12)),
                ('stock', models.IntegerField(default=0, help_text='Available stock')),
                ('instant_delivery', models.BooleanField(default=False, help_text='Available for instant delivery')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for instant delivery', max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for standard shipping', max_digits=10)),
                ('pickup_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for in-person pickup', max_digits=10)),
                ('max_delivery_distance', models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum delivery distance in km', max_digits=5)),
                ('min_order_quantity', models.IntegerField(default=1, help_text='Minimum order quantity')),
                ('max_order_quantity', models.IntegerField(default=100, help_text='Maximum order quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Product',
                'verbose_name_plural': 'Vendor Products',
                'unique_together': {('vendor', 'product')},
            },
        ),
    ]
