# Generated by Django 4.2.19 on 2025-02-22 12:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oscar.core.utils
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0018_alter_line_num_allocated'),
        ('basket', '0012_line_code'),
        ('sites', '0002_alter_domain_unique'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorproduct',
            options={'verbose_name': 'Vendor Product', 'verbose_name_plural': 'Vendor Products'},
        ),
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'ordering': ('name', 'code'), 'permissions': (('dashboard_access', 'Can access dashboard'),), 'verbose_name': 'Vendor Profile', 'verbose_name_plural': 'Vendor Profiles'},
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.basket', verbose_name='Basket'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.billingaddress', verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=12, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='date_placed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Guest email address'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='number',
            field=models.CharField(default='ORD-20250222-121941-784866', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.shippingaddress', verbose_name='Shipping Address'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='shipping_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='shipping_excl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping charge (excl. tax)'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='shipping_incl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping charge (inc. tax)'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=128, verbose_name='Shipping method'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='shipping_tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Shipping VAT rate code'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='total_excl_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='total_incl_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Low Stock Threshold'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='num_allocated',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number allocated'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='num_in_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number in stock'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_stockrecords', to='marketplace.vendorprofile'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='partner_sku',
            field=models.CharField(default='SKU-20250222-121823', max_length=128),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='price_currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=12, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bond_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='code',
            field=oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from='name', unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='marketplace_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_stockrecords', to='catalogue.product'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vendorproduct',
            unique_together={('partner', 'partner_sku')},
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='vendor',
        ),
    ]
