# Generated by Django 4.2.19 on 2025-02-22 12:26

from django.db import migrations, models
import django.db.models.deletion
import marketplace.models.vendor


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
        ('marketplace', '0002_alter_vendorproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('GB', 'United Kingdom'), ('EU', 'European Union'), ('CA', 'Canada'), ('AU', 'Australia')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='partner_sku',
            field=models.CharField(default=marketplace.models.vendor.VendorProduct.generate_sku, max_length=128),
        ),
        migrations.CreateModel(
            name='PostageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postage_options', to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Postage Option',
                'verbose_name_plural': 'Postage Options',
                'ordering': ['price'],
            },
        ),
    ]
